default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: TalentLink_development

test:
  <<: *default
  database: TalentLink_test

production:
  <<: *default
  database: TalentLink_production
  username: TalentLink
  password: <%= ENV["TALENTLINK_DATABASE_PASSWORD"] %>
